name: Release Creation

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build

      - name: Extract tag version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "dist/module.json"
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/dfreds-droppables.zip

      - name: Zip files
        working-directory: ./dist
        run: zip -r ./dfreds-droppables.zip ./*

      - name: Get changes between tags
        id: changes
        uses: simbo/changes-between-tags-action@v1

      - name: Create versioned release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          artifacts: "./dist/module.json, ./dist/dfreds-droppables.zip"
          body: "${{ steps.changes.outputs.changes }} \n ${{ github.event.release.body }}"
          draft: true
          generateReleaseNotes: true
          name: ${{ github.event.release.name }}
          tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
